GO

CREATE TABLE [dbo].[_DatabaseVersion](
	[Id] [int] NOT NULL,
	[DbVersion] [varchar](16) NOT NULL,
 CONSTRAINT [PK__DatabaseVersion] PRIMARY KEY CLUSTERED 
(
	[Id] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO

ALTER TABLE [dbo].[_DatabaseVersion] ADD  CONSTRAINT [DF__DatabaseVersion_DbVersion]  DEFAULT (CONVERT([varchar],getutcdate(),(4))) FOR [DbVersion]
GO
GO