CREATE TABLE [dbo].[AchTypes](
    [Id] [int] IDENTITY(1,1) NOT NULL,
    [Type] [nvarchar](5) NOT NULL,
    [Description] [nvarchar](100) NULL,
    CONSTRAINT [PK_AchTypes] PRIMARY KEY CLUSTERED
(
[Id] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
    ) ON [PRIMARY]
    GO