CREATE TABLE [dbo].[Coverages](
	[Id] [int] IDENTITY(1,1) NOT NULL,
	[CoverageType] [nvarchar](50) NOT NULL,
	[CoverageLimit] [int] NOT NULL,
 CONSTRAINT [PK_Coverages] PRIMARY KEY CLUSTERED 
(
	[Id] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO
