CREATE TABLE [dbo].[Gvwr](
	[Id] [int] IDENTITY(1,1) NOT NULL,
	[ClassDescription] [nvarchar](70) NOT NULL,
 CONSTRAINT [PK_Gvwr] PRIMARY KEY CLUSTERED 
(
	[Id] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO
