CREATE TABLE [dbo].[InsuredVehicle](
	[Id] [int] IDENTITY(1,1) NOT NULL,
	[InsuredId] [int] NOT NULL,
	[TrackId] [int] NULL,
	[TrailId] [int] NULL,
	[VehicleId] [int] NOT NULL,
 CONSTRAINT [PK_InsuredVehicle] PRIMARY KEY CLUSTERED 
(
	[Id] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO