CREATE TABLE [dbo].[MessageAttachments](
	[MessageId] [bigint] NOT NULL,
	[AttachmentId] [int] NOT NULL,
 CONSTRAINT [PK_MessageAttachments_1] PRIMARY KEY CLUSTERED 
(
	[MessageId] ASC,
	[AttachmentId] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]