<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net6.0</TargetFramework>
  </PropertyGroup>

  <ItemGroup>
    <Compile Remove="APIRequestModels\**" />
    <EmbeddedResource Remove="APIRequestModels\**" />
    <None Remove="APIRequestModels\**" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\Domain\Domain.csproj" />
    <ProjectReference Include="..\System.Common\System.Common.csproj" />
  </ItemGroup>

  <ItemGroup>
    <Folder Include="Request\Outlook\" />
  </ItemGroup>

</Project>
